// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbodmwihidinmxympwip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhib2Rtd2loaWRpbm14eW1wd2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MzkxNzQsImV4cCI6MjA3MzIxNTE3NH0.iT3nOSR61ZTnYi09JyA4VDxVpUCNMYpAoLjYBGTwHGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});